### PR TITLE
Parse odrdate in correct tz

### LINKED ISSUE #137: odrdate is incorrectly parsed into UTC
```
DEBUG:smart_meter_texas:Reading completed: {'odrstatus': 'COMPLETED', 
'odrread': '88612.961', 'odrusage': '62.503', 'odrdate': '07/22/2023 22:50:28', 
'responseMessage': 'SUCCESS'}
```

The above `odrdate` is in America/Chicago timezone. `reading_datetime()` parses it as UTC. Storing this value in a database (influxdb, for example) to be presented in a graph (grafana, for example), all of the times are skewed by 5hrs.

Consider the following code change to parse the timestamp as America/Chicago first, then convert to UTC

```
from dateutil.tz import gettz
...
    @property
    def reading_datetime(self):
        date = dateutil.parser.parse(self.reading_data["odrdate"]).replace(tzinfo=gettz("America/Chicago"))
        date_as_utc = date.astimezone(datetime.timezone.utc)
        return date_as_utc
```

Debugging:
```
>>> d=dateutil.parser.parse("07/22/2023 22:50:28")
>>> f=d.astimezone(datetime.timezone.utc)
>>> d
datetime.datetime(2023, 7, 22, 22, 50, 28)
>>> f
datetime.datetime(2023, 7, 22, 22, 50, 28, tzinfo=datetime.timezone.utc)    <--- this is not correct


>>> d=dateutil.parser.parse("07/22/2023 22:50:28").replace(tzinfo=gettz("America/Chicago"))
>>> f=d.astimezone(datetime.timezone.utc)
>>> d
datetime.datetime(2023, 7, 22, 22, 50, 28, tzinfo=tzfile('/usr/share/zoneinfo/America/Chicago'))
>>> f
datetime.datetime(2023, 7, 23, 3, 50, 28, tzinfo=datetime.timezone.utc)   <-- correct UTC
```

### PR DESCRIPTION
**Pull request by utdrmac**
Resolves #137

### CODE REVIEW

**Comment by utdrmac** [comment]
Since America/Chicago is subject to DST, I opted to use gettz() vs a static -5h/-6h offset.

**Review by grahamwetzler — CHANGES_REQUESTED** [review]
Thanks! Makes sense. Just need to run isort to get the imports consistent

**Comment by utdrmac** [comment]
I don't understand what you mean by isort?

**Comment by utdrmac** [comment]
I googled it. Found it. Ran it.

**Review by grahamwetzler — APPROVED** [review]
Thanks!

**Pull request merged**
